#!/usr/bin/env bash
set -euo pipefail
python3 tools/audit_repo.py | tee audit.json
python3 - "$@" <<'PY'
import json, pathlib
j=json.load(open('audit.json'))
missing='\n'.join(f"- {x}" for x in j['missing_files']) or '- None'
ci_m='\n'.join(f"- {x}" for x in j['ci_missing']) or '- None'
d_m='\n'.join(f"- {x}" for x in j['docs_missing']) or '- None'
stubs=[]
for f, hits in j['stub_findings'].items():
    stubs.append('### '+f+'\n'+'\n'.join(f"- line {h['line']}: {h['pattern']}" for h in hits))
stubs='\n\n'.join(stubs) or '_No stub patterns found._'
md=f"""# EcoMate Repo Audit — Snapshot

## Missing Expected Files
{missing}

## Stub/Placeholder Findings
{stubs}

## CI Workflows Missing
{ci_m}

## Roadmap Docs Missing
{d_m}

_Generated by tools/audit_repo.py_
"""
pathlib.Path('AUDIT_REPORT.md').write_text(md)
print('Wrote AUDIT_REPORT.md')
PY