name: Repo Audit
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '23 4 * * 1'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -U pip
      - run: bash tools/audit_report.sh
      - name: Commit report
        run: |
          if [ -n "$(git status --porcelain AUDIT_REPORT.md audit.json)" ]; then
            git config user.name "eco-bot"; git config user.email "bot@users.noreply.github.com"
            git add AUDIT_REPORT.md audit.json
            git commit -m "chore(audit): update report"
          fi
      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(audit): weekly repo audit report"
          branch: chore/audit-report
          commit-message: "chore(audit): update report"
          body: "Automated audit report update."